services:
  db:
    image: timescale/timescaledb-ha:pg16
    container_name: plane_tracker_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=flight_data
    ports:
      - "15000:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: admin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  timescale_data: